### ISSUE TITLE
Incompatibility with dplyr 1.0.0

### ISSUE THREAD

**Issue by bersbersbers** [lujunyan1118/DrugScreenExplorer#1]
It seems to me that DSE is incompatible with dplyr 1.0.0, see more details at https://stackoverflow.com/q/62638400/. Data that can be processed with dplyr 0.8.5 installed fails with dplyr 1.0.0 installed:

> Error: `...` is not empty.
> 
> We detected these problematic arguments:
> * `..1`
> 
> These dots only exist to allow future extensions and should be empty.
> Did you misspecify an argument? Run `rlang::last_error()` to see where
> the error occurred.

**Comment by bersbersbers** [comment]
I believe this is fixed as of 7c9859919a0d5befdaf93498cb330f0d23d1878d. Would have been great to receive this information here ;)

**Comment by lujunyan1118** [comment]
Thanks for the comment. Sorry that I didn't notice the message earlier.
