### ISSUE TITLE
Breaking change in column formats

### ISSUE THREAD

**Issue by bersbersbers** [lujunyan1118/DrugScreenExplorer#2]
https://github.com/lujunyan1118/DrugScreenExplorer/commit/45333d8be07c40dd2c0dd9a6c4855b4724f8ec33 changes the column ID format, as can be seen here:

![image](https://user-images.githubusercontent.com/12128514/86587908-e06f3d00-bf8a-11ea-8bc9-0eac8a35d8fb.png)

This obviously breaks existing code. Was that an accidental change or is it here to stay?

**Comment by lujunyan1118** [comment]
Thanks for the comment.  The "01", "02", "03" format is the intended way.
